### ISSUE TITLE
请问如何迁移存档的地图和传送点？

### ISSUE THREAD

**Issue by Excitablecell** [GalileoFe/PalWorld-Save-Movement-Complete-Tutorio#1]
您在服务器间迁移存档那里也提到了会丢失地图和传送点的问题
请问这个有办法解决吗

**Comment by GalileoFe** [comment]
目前暂时没有办法解决

**Comment by GalileoFe** [comment]
@Excitablecell 你可以试着看看自己的电脑里是否仍然拥有localdata.sav这个文件，这个文件决定了玩家的地图进度。

**Comment by 1803233552** [comment]
参考这个迁移地图进度 https://github.com/xNul/palworld-host-save-fix/issues/105
