### ISSUE TITLE
可不可以讲一下linux上不加载steamclient.so的服务端是怎么安装的

### ISSUE THREAD

**Issue by BraveCowardp** [GalileoFe/PalWorld-Save-Movement-Complete-Tutorio#10]
见过win上不加载steam库的，也见过win和linux上有appid的，但没有见过linux上不加载steamclient,so的服务端，如果win上不加载steam库的存档往linux上转就不会转了

**Comment by BraveCowardp** [comment]
[https://github.com/GalileoFe/PalWorld-Save-Movement-Complete-Tutorio?tab=readme-ov-file#%E9%87%8D%E5%BB%BA%E6%B8%B8%E6%88%8F%E8%A7%92%E8%89%B2](url)
我看到这里了，但是linux上删除~/.steam会导致加载steamclient.so一直报错
![Uploading image.png…]()

**Comment by BraveCowardp** [comment]
> 对于Linux用户：
> 
> 删除 ~/.steam/sdk64 这个文件夹来处理游戏角色的重建问题。

我看到这里了，但是删掉这个文件夹后会导致找不到steamclient.so一直报错
![image](https://github.com/GalileoFe/PalWorld-Save-Movement-Complete-Tutorio/assets/61410850/dc924887-7e0e-4836-b3b1-b56c4528b68b)

**Comment by GalileoFe** [comment]
> > 对于Linux用户：
> > 删除 ~/.steam/sdk64 这个文件夹来处理游戏角色的重建问题。
> 
> 我看到这里了，但是删掉这个文件夹后会导致找不到steamclient.so一直报错 ![image](https://private-user-images.githubusercontent.com/61410850/301231642-dc924887-7e0e-4836-b3b1-b56c4528b68b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTg3MjYsIm5iZiI6MTcwNjcxODQyNiwicGF0aCI6Ii82MTQxMDg1MC8zMDEyMzE2NDItZGM5MjQ4ODctN2UwZS00ODM2LWIzYjEtYjU2YzQ1MjhiNjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE2MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYTNmMDdhMWExYmExY2JlMmUxYzY0ZWNiMjNlYzFkMDk5NmM3NTY2MjljZjdhZWQ3ZDk0MzM3YzJlZWMwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwxxLjcv93xW4M0fJ5d9UtmhYlt80CVoGs-MzRqd5wM)

报错就证明成功了，上线开始享受游戏吧

**Comment by BraveCowardp** [comment]
> > > 对于Linux用户：
> > > 删除 ~/.steam/sdk64 这个文件夹来处理游戏角色的重建问题。
> > 
> > 
> > 我看到这里了，但是删掉这个文件夹后会导致找不到steamclient.so一直报错 ![image](https://private-user-images.githubusercontent.com/61410850/301231642-dc924887-7e0e-4836-b3b1-b56c4528b68b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTg3MjYsIm5iZiI6MTcwNjcxODQyNiwicGF0aCI6Ii82MTQxMDg1MC8zMDEyMzE2NDItZGM5MjQ4ODctN2UwZS00ODM2LWIzYjEtYjU2YzQ1MjhiNjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE2MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYTNmMDdhMWExYmExY2JlMmUxYzY0ZWNiMjNlYzFkMDk5NmM3NTY2MjljZjdhZWQ3ZDk0MzM3YzJlZWMwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwxxLjcv93xW4M0fJ5d9UtmhYlt80CVoGs-MzRqd5wM)
> 
> 报错就证明成功了，上线开始享受游戏吧

感谢
