### ISSUE TITLE
WinServer迁移Linux没成功

### ISSUE THREAD

**Issue by ErYiii** [GalileoFe/PalWorld-Save-Movement-Complete-Tutorio#3]
不知道是不是我的问题，我把WinServer上的存档，替换到Linux上，也改了配置文件。一启动服务CPU就爆了然后服务挂掉。  恢复成替换前的状态就能正常运行

**Comment by GalileoFe** [comment]
没见过的错误呢，是不是存档坏掉了？你在以前的winserver还能用吗，存档

**Comment by GalileoFe** [comment]
> 不知道是不是我的问题，我把WinServer上的存档，替换到Linux上，也改了配置文件。一启动服务CPU就爆了然后服务挂掉。 恢复成替换前的状态就能正常运行

请你补充，是否使用docker？

**Comment by GalileoFe** [comment]
#7

**Comment by GalileoFe** [comment]
修改文件夹权限即可
