### ISSUE TITLE
关于steamcmd模式下安装服务程序的问题

### ISSUE THREAD

**Issue by Hope6537** [GalileoFe/PalWorld-Save-Movement-Complete-Tutorio#4]
都是使用steamcmd安装的游戏
A服务器运行时有
Setting breakpad minidump AppID = 1623730

B服务器运行时无

都只运行了一下命令
steamcmd +login anonymous +app_update 2394010 validate +quit
求解如何处理

**Comment by GalileoFe** [comment]
安装steam客户端或者使用steamcmd condenser 使steamcmd库文件可以正常加载
