### ISSUE TITLE
Windows Server异常退出

### ISSUE THREAD

**Issue by 2exd** [GalileoFe/PalWorld-Save-Movement-Complete-Tutorio#6]
我在Windows server之间进行存档迁移，迁移后遇到了角色重建问题。
我按照[这里的步骤](https://github.com/GalileoFe/PalWorld-Save-Movement-Complete-Tutorio/tree/main?tab=readme-ov-file#%E5%9C%A8part-ii%E9%87%8D%E5%BB%BA%E7%8E%A9%E5%AE%B6%E5%AD%98%E6%A1%A3%E4%B9%8B%E5%90%8E%E4%BB%8D%E9%9C%80%E8%A6%81%E6%96%B0%E5%BB%BA%E8%A7%92%E8%89%B2)操作后，启动pal server，再启动游戏客户端连接server时，server cmd窗口会直接退出。
请问有相关的解决方案吗？

**Comment by GalileoFe** [comment]
存档验证失败导致游戏崩溃。
服务器之间进行存档迁移不需要使用PART II的步骤替换文件

**Comment by GalileoFe** [comment]
直接，有steam的替换有steam的。无steam的替换无steam的。
使用16进制编辑器看看角色.sav是不是空存档，有可能存档空的坏掉了

**Comment by 2exd** [comment]
> 存档验证失败导致游戏崩溃。 服务器之间进行存档迁移不需要使用PART II的步骤替换文件

那就回到第一个问题了，存档迁移后出现需要新建角色的情况。

**Comment by GalileoFe** [comment]
> > 存档验证失败导致游戏崩溃。 服务器之间进行存档迁移不需要使用PART II的步骤替换文件
> 
> 那就回到第一个问题了，存档迁移后出现需要新建角色的情况。

如果前一个服务器上服务器是无ID的模式，新服务器上服务器也应该是无ID（运行时cmd为空）的状态。
反之同理
